version: "2"

services:
  purl_db:
    build:
      context: ./purl_db_Dockerfile
      dockerfile: Dockerfile
    image: "postgres_ja"
    container_name: "purl_db"
    ports:
      - "15432:5432"
    restart: unless-stopped
    volumes:
      - "$PWD/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=irjwtYAh7u@Wejo
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
  purl_web_apache:
    build:
      context: ./purl_apache_Dockerfile
      dockerfile: Dockerfile
    image: "rails_for_purl_apache"
    container_name: "purl_web_apache"
    ports:
      - "13000:3000"
    restart: unless-stopped
    volumes:
      - "$PWD/contents:/opt/rails_5.2.2/purl"
    working_dir: "/opt/rails_5.2.2/purl"
    command:
      - /run_in_container.sh
    tty: true
